### User Settings REST Client Tests
@baseUrl = http://localhost:8080/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTMyOTFmNDZhOTAwMDQyMWVjNzYyMjIiLCJyb2xlSWQiOjIsImlhdCI6MTc4MTg3NDEzOCwiZXhwIjoyNjQ1ODc0MTM4fQ.bdHXpekE-IfKeF5GTfuvBrM5IuBzsD4gXp8zhP-1mhk

### 1. Get User Settings (Should return defaults if not set)
GET {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json


### 2. Update All Settings to True
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookingNotification": false
  # "pushNotification": false,
  # "reminderNotification": true,
  # "organizerUpdateNotification": true,
  # "messageNotification": true
}


### 3. Toggle pushNotification (Main) to False (Should turn off all sub-notification preferences)
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pushNotification": true
}


### 4. Toggle pushNotification (Main) back to True (Should turn on all sub-notification preferences)
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pushNotification": true
}


### 5. Independently update sub-preference when main (pushNotification) is true
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookingNotification": false,
  "messageNotification": false
}


### 6. Auto-disable pushNotification if all sub-notification preferences are toggled to false
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookingNotification": false,
  "reminderNotification": false,
  "organizerUpdateNotification": false,
  "messageNotification": false
}


### 7. Auto-enable pushNotification if any sub-notification preference is toggled to true
POST {{baseUrl}}/userSetting
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "messageNotification": true
}
