module.exports = {
  user: require("./controller/controllerUser"),
  category: require("./controller/controllerCategory"),
  event: require("./controller/controllerEvent"),
  tax: require("./controller/controllerTax"),
  promocode: require("./controller/controllerPromoCode"),
  follow: require("./controller/controllerFollow"),
  block: require("./controller/controllerBlock"),
  report: require("./controller/controllerReport"),
  verification: require("./controller/controllerVerification"),
  booking: require("./controller/controllerBooking"),
  course: require("./controller/controllerCourse"),
  payout: require("./controller/controllerPayout"),
  globalsetting: require("./controller/controllerGlobalSetting"),
  faq: require("./controller/controllerFAQ"),
  comment: require("./controller/controllerComment"),
  chat: require("./controller/controllerChat"),
  review: require("./controller/controllerReview"),
  support: require("./controller/controllerSupportTicket"),
  notification: require("./controller/controllerNotification"),
  analytics: require("./controller/controllerAnalytics"),
  attendee: require("./controller/controllerAttendee"),
  contact: require("./controller/controllerContact"),
  supportTicket: require("./controller/controllerSupportTicket"),
  organizerStats: require("./controller/controllerOrganizerStats"),
  wishlist: require("./controller/controllerWishlist"),
  userSetting: require("./controller/controllerUserSetting"),
  "promotion-package": require("./controller/controllerPromotionPackage"),
  "event-promotion": require("./controller/controllerEventPromotion"),
  "course-promotion": require("./controller/controllerCoursePromotion"),
  referral: require("./controller/controllerReferral"),
};


