module.exports = {
  user: require("./controller/controllerUser"),
  category: require("./controller/controllerCategory"),
  event: require("./controller/controllerEvent"),
  tax: require("./controller/controllerTax"),
  promocode: require("./controller/controllerPromoCode"),
  follow: require("./controller/controllerFollow"),
  block: require("./controller/controllerBlock"),
  report: require("./controller/controllerReport"),
  verification: require("./controller/controllerVerification"),
  booking: require("./controller/controllerBooking"),
  course: require("./controller/controllerCourse"),
  payout: require("./controller/controllerPayout"),
  globalsetting: require("./controller/controllerGlobalSetting"),
  faq: require("./controller/controllerFAQ"),
  comment: require("./controller/controllerComment"),
  chat: require("./controller/controllerChat"),
};
