module.exports = Object.freeze({
  REGISTRATION_SUCCESS_MESSAGE: "Registered successfully.",
  REGISTRATION_FAILURE_MESSAGE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  REGISTRATION_DEVICE_ID_FAIL:
    "Please Register With Same Device as You Verified Earliar.",
  LOGIN_SUCCESS: "Login Successful.",
  ACCOUNT_DISABLE: "Account Disable",
  LOGIN_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  EMAIL_NOTFOUND: "Email not Found",
  INVALID_PASSWORD: "Invalid Password",
  UPDATE_PASSWORD_SUCCESS: "Your password is successfully updated.",
  UPDATE_PASSWORD_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED_MSG:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED: "Server error.",
  INNGS_DUPLICATE: "Inngs duplicate data already exist.",
  CREATE_SUCCESS: "Created successfully.",
  SUCCESS: "success",
  ALREADY: "Already exist.",
  DULICATE: "Name/mobile number are already exist.",
  NOT_FOUND: "Not found.",
  DATABASE_ERROR: "Not Getting Parent",
  FAILED_TO_SAVE: "Failed to save user data",
  PASSWORD_NOT_MATCH: "Password and ConfirmPassword not match",
  REGISTRATION_OTP: "OTP has been sent to your registered email",
  CREDENTIALS: "Enter valid credentials",
  OLD_PASSWORD: "Old password is incorrect",
  SEND_OTP: "OTP sent to your email address. OTP will expire in 10 min.",
  UPDATE_STATUS: "Update Status Successfully",
  WITHDRAW_AMOUNT:
    "Withdrawa request approved and balance deducted successfully.",
  WITHDRAW_REQUEST: "Withdraw request initiated successfully.",
  DEPOSIT_AMOUNT: "Deposit amount request initiated successfully.",
  UPDATE_BANK: "Bank details updated successfully.",
  ADD_BANK: "Bank details added successfully.",
  DEVICE_ID: `dLNvpQxZRPykx96jvtjKss:APA91bE6zNwVmvz0TXTwr9Ijl-rkaurwi0WAYx42wq-G3iPSOl04DMjbVAXHDzevxeT2fWtKvmfO_73R9PQ095RPashK8BmNJ8_NTCOB49F2ZZDuw0uN_1TFgm30NgrrYEjXdkiJv4Ho`,
  ACCOUNT_DISABLED: "Your account has been disabled. Please contact support.",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  CONTACT_ALREADY_EXISTS: "Contact number already exists",
  OTP_SENT_SUCCESS: "OTP sent successfully",
  INVALID_OR_EXPIRED_OTP: "Invalid or expired OTP",
  SESSION_EXPIRED_REGISTER: "Session expired, please register again",
  SESSION_EXPIRED_SIGNUP:
    "Session expired or invalid request. Please start signup again.",
  REGISTRATION_SUCCESSFUL: "Registration successful",
  ORGANIZER_REGISTRATION_SUCCESS:
    "Organizer registration successful. Pending admin approval.",
  OTP_RESENT_SUCCESS: "OTP resent successfully",
  NO_FILES_UPLOADED: "No files uploaded",
  FILES_UPLOADED_SUCCESS: "Files uploaded successfully",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  USER_NOT_FOUND: "User not found",
  LOGIN_SUCCESS_MSG: "Login successful",
  ACCOUNT_STATUS_PREFIX: "Your account status is ",
  WAIT_FOR_ADMIN_APPROVAL: ". Please wait for admin approval.",
  CATEGORY_NAME_REQUIRED: "Category name is required.",
  CATEGORY_RESTORED: "Category restored successfully.",
  CATEGORY_ALREADY_EXISTS: "Category already exists.",
  CATEGORY_CREATED: "Category created successfully.",
  CATEGORIES_FETCHED: "Categories fetched successfully.",
  CATEGORY_NOT_FOUND: "Category not found.",
  CATEGORY_NAME_DUPLICATE: "Category with this name already exists.",
  CATEGORY_UPDATED: "Category updated successfully.",
  CATEGORY_DELETED: "Category deleted successfully.",
  PROFILE_UPDATED: "Profile updated successfully.",
  SUPER_ADMIN_UPDATE_NOT_ALLOWED:
    "Updating super admin profile is not allowed.",
  EVENT_CREATED: "Event created successfully.",
  EVENTS_FETCHED: "Events fetched successfully.",
  INVALID_FILTER_TYPE: "Invalid filter type provided.",
  LOCATION_REQUIRED: "Latitude and longitude are required for nearYou filter.",
});
