module.exports = Object.freeze({
  REGISTRATION_SUCCESS_MESSAGE: "Registered successfully.",
  REGISTRATION_FAILURE_MESSAGE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  REGISTRATION_DEVICE_ID_FAIL:
    "Please Register With Same Device as You Verified Earliar.",
  LOGIN_SUCCESS: "Login Successful.",
  GUEST_LOGIN_SUCCESS: "Guest login successful",
  ACCOUNT_DISABLE: "Account Disable",
  LOGIN_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  EMAIL_NOTFOUND: "Email not Found",
  INVALID_PASSWORD: "Invalid Password",
  UPDATE_PASSWORD_SUCCESS: "Your password is successfully updated.",
  UPDATE_PASSWORD_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED_MSG:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED: "Server error.",
  INNGS_DUPLICATE: "Inngs duplicate data already exist.",
  CREATE_SUCCESS: "Created successfully.",
  SUCCESS: "success",
  ALREADY: "Already exist.",
  DULICATE: "Name/mobile number are already exist.",
  NOT_FOUND: "Not found.",
  DATABASE_ERROR: "Not Getting Parent",
  FAILED_TO_SAVE: "Failed to save user data",
  PASSWORD_NOT_MATCH: "Password and ConfirmPassword not match",
  REGISTRATION_OTP: "OTP has been sent to your registered email",
  CREDENTIALS: "Enter valid credentials",
  OLD_PASSWORD: "Old password is incorrect",
  SEND_OTP: "OTP sent to your email address. OTP will expire in 10 min.",
  UPDATE_STATUS: "Update Status Successfully",
  WITHDRAW_AMOUNT:
    "Withdrawa request approved and balance deducted successfully.",
  WITHDRAW_REQUEST: "Withdraw request initiated successfully.",
  DEPOSIT_AMOUNT: "Deposit amount request initiated successfully.",
  UPDATE_BANK: "Bank details updated successfully.",
  ADD_BANK: "Bank details added successfully.",
  DEVICE_ID: `dLNvpQxZRPykx96jvtjKss:APA91bE6zNwVmvz0TXTwr9Ijl-rkaurwi0WAYx42wq-G3iPSOl04DMjbVAXHDzevxeT2fWtKvmfO_73R9PQ095RPashK8BmNJ8_NTCOB49F2ZZDuw0uN_1TFgm30NgrrYEjXdkiJv4Ho`,
  ACCOUNT_DISABLED: "Your account has been disabled. Please contact support.",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  CONTACT_ALREADY_EXISTS: "Contact number already exists",
  OTP_SENT_SUCCESS: "OTP sent successfully",
  INVALID_OR_EXPIRED_OTP: "Invalid or expired OTP",
  SESSION_EXPIRED_REGISTER: "Session expired, please register again",
  SESSION_EXPIRED_SIGNUP:
    "Session expired or invalid request. Please start signup again.",
  REGISTRATION_SUCCESSFUL: "Registration successful",
  ORGANIZER_REGISTRATION_SUCCESS:
    "Organizer registration successful. Pending admin approval.",
  OTP_RESENT_SUCCESS: "OTP resent successfully",
  NO_FILES_UPLOADED: "No files uploaded",
  FILES_UPLOADED_SUCCESS: "Files uploaded successfully",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  USER_NOT_FOUND: "User not found",
  LOGIN_SUCCESS_MSG: "Login successful",
  ACCOUNT_STATUS_PREFIX: "Your account status is ",
  WAIT_FOR_ADMIN_APPROVAL: ". Please wait for admin approval.",
  CATEGORY_NAME_REQUIRED: "Category name is required.",
  CATEGORY_RESTORED: "Category restored successfully.",
  CATEGORY_ALREADY_EXISTS: "Category already exists.",
  CATEGORY_CREATED: "Category created successfully.",
  CATEGORIES_FETCHED: "Categories fetched successfully.",
  CATEGORY_NOT_FOUND: "Category not found.",
  CATEGORY_NAME_DUPLICATE: "Category with this name already exists.",
  CATEGORY_UPDATED: "Category updated successfully.",
  CATEGORY_DELETED: "Category deleted successfully.",
  PROFILE_UPDATED: "Profile updated successfully.",
  SUPER_ADMIN_UPDATE_NOT_ALLOWED:
    "Updating super admin profile is not allowed.",
  EVENT_CREATED: "Event created successfully.",
  EVENT_NOT_FOUND: "Event not found.",
  EVENTS_FETCHED: "Events fetched successfully.",
  EVENT_SLIDER_UPDATED: "Event slider status updated successfully.",
  EVENT_SLIDER_ONLY_UPCOMING_LIVE:
    "Only Upcoming or Live events can be added to slider.",
  INVALID_FILTER_TYPE: "Invalid filter type provided.",
  LOCATION_REQUIRED: "Latitude and longitude are required for nearYou filter.",
  ACCESS_DENIED_INVALID_ROLE: "Access denied. Invalid role.",
  ACCESS_DENIED_ADMIN_ONLY: "Access denied. Admin only.",
  USER_DELETED_SUCCESS: "User deleted successfully",
  ACCOUNT_DELETED_SUCCESS: "Account deleted successfully",
  COURSE_CREATED_SUCCESS: "Course created successfully",
  COURSE_UPDATED_SUCCESS: "Course updated successfully",
  COURSE_UPDATE_FAILED: "Failed to update course",
  UNAUTHORIZED_COURSE_EDIT: "You are not authorized to edit this course",
  UNAUTHORIZED_EVENT_UPDATE: "Unauthorized to update this event",
  DRAFT_UPDATED: "Draft updated",
  EVENT_PUBLISHED_SUCCESS: "Event published successfully",
  DRAFT_SAVED: "Draft saved",
  LOGIN_REQUIRED_DRAFTS: "Login required to view drafts",
  CANNOT_FOLLOW_SELF: "You cannot follow yourself.",
  ALREADY_FOLLOWING: "Already following this user.",
  FOLLOW_SUCCESS: "User followed successfully.",
  NOT_FOLLOWING: "You are not following this user.",
  UNFOLLOW_SUCCESS: "User unfollowed successfully.",
  FOLLOWERS_FETCHED: "Followers fetched successfully.",
  FOLLOWING_FETCHED: "Following list fetched successfully.",
  BUG_REPORT_SUCCESS: "Bug reported successfully",
  BUGS_FETCHED: "Bugs fetched successfully",
  TITLE_REQUIRED: "Title is required",
  INTERNAL_SERVER_ERROR: "Internal server error",
  UNAUTHORIZED_ACCESS: "Access denied. Unauthorized access.",
  SCHEDULE_DATE_ERROR: "Schedule start date must be before end date",
  FIXED_START_SCHEDULE_ERROR: "Fixed start courses must have exactly one schedule",
  DOCUMENTS_REQUIRED: "At least one document is required.",
  ALREADY_VERIFIED: "You are already verified. Re-submission is not allowed.",
  VERIFICATION_DOCS_UPDATED: "Verification documents updated successfully.",
  INVALID_VERIFICATION_ACTION: "Invalid action. Use 'approve' or 'reject'.",
  DOCUMENT_ID_REQUIRED: "Document ID is required.",
  BUSINESS_PROOF_REJECTION_ERROR: "Approved 'Business Proof' cannot be rejected.",
  REJECTION_REASON_REQUIRED: "Reason is required for rejection.",
  DOCUMENT_STATUS_UPDATED: "Document status updated successfully.",
  USER_SETTING_FETCHED: "User setting fetched successfully",
  USER_SETTING_UPDATED: "User setting updated successfully",
  VERIFICATION_REQUESTS_FETCHED: "Verification requests fetched successfully.",
  DOCUMENT_NOT_FOUND: "Document not found.",
  CATEGORY_STATS_FETCHED: "Category statistics fetched successfully",
  INVALID_ENTITY_MODEL: "Invalid entity model",
  PARENT_COMMENT_NOT_FOUND: "Parent comment not found",
  COMMENT_ADDED: "Comment added successfully",
  COMMENTS_FETCHED: "Comments fetched successfully",
  COMMENT_NOT_FOUND_OR_UNAUTHORIZED: "Comment not found or you are not authorized",
  COMMENT_UPDATED: "Comment updated successfully",
  COMMENT_DELETED: "Comment deleted successfully",
  COMMENT_NOT_FOUND: "Comment not found",
  COMMENT_UNLIKED: "Comment unliked",
  COMMENT_LIKED: "Comment liked",
  PARENT_COMMENT_ID_REQUIRED: "parentCommentId is required",
  REPLIES_FETCHED: "Replies fetched successfully",
  ENTITY_NOT_FOUND: "Entity not found",
  REVIEW_ADDED: "Review added successfully",
  REVIEW_NOT_FOUND_OR_UNAUTHORIZED: "Review not found or not authorized",
  REVIEW_UPDATED: "Review updated successfully",
  REVIEW_DELETED: "Review deleted successfully",
  REVIEWS_FETCHED: "Reviews fetched successfully",
  ORGANIZER_REVIEWS_FETCHED: "Organizer reviews fetched successfully",
  ITEM_ALREADY_IN_WISHLIST: "Item already in wishlist",
  ADDED_TO_WISHLIST: "Added to wishlist",
  ITEM_NOT_FOUND_IN_WISHLIST: "Item not found in wishlist",
  REMOVED_FROM_WISHLIST: "Removed from wishlist",
  WISHLIST_FETCHED: "Wishlist fetched successfully",
  NOTIFICATIONS_FETCHED: "Notifications fetched successfully",
  NOTIFICATION_MARKED_READ: "Notification marked as read",
  ALL_NOTIFICATIONS_MARKED_READ: "All notifications marked as read",
  NOTIFICATION_DELETED: "Notification deleted",
  NOT_ENOUGH_TICKETS: "Not enough tickets available",
  NOT_ENOUGH_SEATS: "Not enough seats available",
  EVENT_OR_COURSE_ID_REQUIRED: "Either eventId or courseId must be provided",
  BOOKING_INITIATED: "Booking initiated",
  PROMO_APPLIED: "Promo code applied successfully",
  INVALID_OR_EXPIRED_PROMO: "Invalid or expired promo code",
  BOOKING_CALCULATION_SUCCESS: "Booking calculation successful",
  TRANSACTION_NOT_FOUND: "Transaction not found",
  TRANSACTION_ALREADY_PAID: "Transaction already paid",
  INVALID_TRANSACTION_STATE: "Transaction is in invalid state to pay",
  REFUND_INITIATED_TICKETS: "Tickets no longer available. Refund initiated.",
  REFUND_INITIATED_SEATS: "Seats no longer available. Refund initiated.",
  BOOKING_CONFIRMED: "Payment successful. Booking confirmed.",
  TICKET_LIST_FETCHED: "Ticket list fetched",
  TICKET_NOT_FOUND: "Ticket not found",
  TICKET_DETAIL_FETCHED: "Ticket detail fetched",
  QR_SCANNED: "QR code scanned",
  EARNINGS_FETCHED: "Earnings fetched successfully",
  BANK_DETAILS_UPDATED: "Bank details updated",
  INVALID_AMOUNT: "Invalid amount",
  INSUFFICIENT_BALANCE: "Insufficient balance",
  PAYOUT_REQUEST_SUBMITTED: "Payout request submitted",
  PENDING_PAYOUTS_FETCHED: "Pending payouts fetched",
  PAYOUT_MARKED_PAID: "Payout marked as paid",
  ADMIN_STATS_FETCHED: "Admin stats fetched",
  PAYOUT_NOT_FOUND: "Payout request not found",
  PAYOUT_NOT_PENDING: "Payout is not pending",
  PAYOUT_APPROVED: "Payout approved",
  PAYOUT_REJECTED: "Payout rejected and refunded",
  FINANCE_STATS_FETCHED: "Finance stats fetched",
  PAYOUTS_FETCHED: "Payouts fetched",
  TRANSACTIONS_FETCHED: "Transactions fetched",
  TAX_ALREADY_EXISTS: "Tax with this name already exists.",
  TAX_CREATED: "Tax created successfully.",
  TAX_UPDATED: "Tax updated successfully.",
  TAX_LIST_FETCHED: "Tax list fetched successfully.",
  TAX_DETAILS_FETCHED: "Tax details fetched successfully.",
  TAX_DELETED: "Tax deleted successfully.",
  PROMO_CODE_EXISTS: "Promo code already exists.",
  PROMO_CODE_CREATED: "Promo code created successfully.",
  PROMO_CODE_UPDATED: "Promo code updated successfully.",
  PROMO_CODES_FETCHED: "Promo codes fetched successfully.",
  PROMO_CODE_DETAILS_FETCHED: "Promo code details fetched successfully.",
  PROMO_CODE_DELETED: "Promo code deleted successfully.",
  BOOKING_EXPIRED: "Booking has expired",
  ALL_TICKETS_CHECKED_IN: "All tickets checked in",
  CHECKED_IN_SUCCESS: "Checked in successfully",
  ATTENDEE_LIST_FORBIDDEN: "You don't have permission to view this event's attendees",
  ATTENDEE_LIST_FETCHED: "Attendees list fetched successfully",
  ATTENDEE_STATS_FORBIDDEN: "You don't have permission to view this event's statistics",
  ATTENDEE_STATS_FETCHED: "Attendee statistics fetched",
  RECENT_BOOKINGS_FETCHED: "Recent bookings fetched successfully",
  PUBLIC_TICKET_DETAIL_FETCHED: "Public ticket detail fetched",
  TICKET_NOT_FOUND_OR_UNAUTHORIZED: "Ticket not found or unauthorized",
  TICKET_URLS_GENERATED: "Ticket URLs generated",
  ORGANIZER_STATS_FETCHED: "Organizer stats fetched successfully",
  CUSTOMER_STATS_FETCHED: "Customer stats fetched successfully",
  USER_STATS_FETCHED: "User specific stats fetched successfully",
  ADMIN_REVENUE_FETCHED: "Admin revenue analytics fetched successfully",
  ORGANIZER_REVENUE_FETCHED: "Organizer revenue analytics fetched successfully",
  TRANSACTION_NOT_FOUND_OR_NOT_PAID: "Transaction not found or not paid",
  ATTENDEES_CREATED: "Attendees created successfully",
  MY_ATTENDEES_FETCHED: "Your attendees fetched successfully",
  ATTENDEE_DETAILS_FETCHED: "Attendee details fetched successfully",
  QR_CODE_REQUIRED: "QR code data is required",
  CANNOT_BLOCK_SELF: "You cannot block yourself.",
  USER_ALREADY_BLOCKED: "User already blocked.",
  USER_BLOCKED: "User blocked successfully.",
  USER_NOT_BLOCKED: "User is not blocked.",
  USER_UNBLOCKED: "User unblocked successfully.",
  BLOCKED_USERS_FETCHED: "Blocked users fetched successfully.",
  NO_FILE_UPLOADED: "No file uploaded",
  FILE_UPLOADED: "File uploaded successfully",
  FILE_UPLOAD_ERROR: "Error uploading file",
  CONTACT_REQUIRED_FIELDS: "Name, Email and Message are required",
  MESSAGE_SENT: "Message sent successfully",
  CONTACTS_FETCHED: "Contacts fetched successfully",
  CONTACT_ID_REQUIRED: "Contact ID is required",
  CONTACT_DELETED: "Contact deleted successfully",
  CONTACT_UPDATE_REQUIRED_FIELDS: "Contact ID and Status are required",
  INVALID_STATUS: "Invalid status",
  CONTACT_NOT_FOUND: "Contact not found",
  CONTACT_STATUS_UPDATED: "Contact status updated successfully",
  COURSE_PROMO_PACKAGES_FETCHED: "Active course promotion packages retrieved successfully",
  COURSE_PROMO_UNAUTHORIZED: "You are not authorized to promote this course",
  PROMO_PACKAGE_NOT_FOUND: "Promotion package not found or inactive",
  PROMO_ACTIVATED: "Promotion activated successfully",
  PROMO_PACKAGES_FETCHED: "Active promotion packages fetched successfully.",
  EVENT_NOT_FOUND_OR_NOT_ORGANIZER: "Event not found or you are not the organizer.",
  EVENT_ALREADY_FEATURED: "This event is already actively featured.",
  FAQS_FETCHED: "FAQs fetched successfully",
  FAQ_CREATED: "FAQ created successfully",
  FAQ_NOT_FOUND: "FAQ not found",
  FAQ_UPDATED: "FAQ updated successfully",
  FAQ_DELETED: "FAQ deleted successfully",
  SETTING_NOT_FOUND: "Setting not found",
  SETTING_FETCHED: "Setting fetched",
  SETTING_UPDATED: "Setting updated",
  SETTINGS_FETCHED: "All settings fetched",
  INVALID_ORGANIZER_ID: "Invalid organizer ID",
  ORGANIZER_TRANSACTIONS_FETCHED: "Organizer transactions fetched successfully",
  FETCH_TRANSACTIONS_FAILED: "Failed to fetch transactions",
  WALLET_HISTORY_FETCHED: "Wallet history fetched successfully",
  FETCH_WALLET_HISTORY_FAILED: "Failed to fetch wallet history",
  PAYOUT_HISTORY_FETCHED: "Payout history fetched successfully",
  FETCH_PAYOUTS_FAILED: "Failed to fetch payouts",
  FETCH_STATS_FAILED: "Failed to fetch statistics",
  ORGANIZER_DASHBOARD_FETCHED: "Organizer dashboard data fetched successfully",
  FETCH_DASHBOARD_FAILED: "Failed to fetch dashboard data",
  FETCH_PROMO_PACKAGES_FAILED: "Active promotion packages fetched successfully.",
  NEW_PROMO_PURCHASED: "New Event Promotion Purchased",
  SERVER_ERROR: "Server Error",
  PROMO_PACKAGE_CREATED: "Promotion package created successfully.",
  PROMO_PACKAGE_UPDATED: "Promotion package updated successfully.",
  PROMO_PACKAGE_DETAILS_FETCHED: "Promotion package details fetched successfully.",
  PROMO_PACKAGE_DELETED: "Promotion package deleted successfully.",
  REFERRAL_CODE_FETCHED: "Referral code fetched",
  REFERRAL_STATS_FETCHED: "Referral stats fetched",
  EMAIL_ALREADY_INVITED: "This email has already been invited by you",
  USER_ALREADY_REGISTERED: "This user is already registered on Bondy",
  INVITE_SENT: "Invite sent successfully",
  REFERRAL_REQUIRED_FIELDS: "referralCode and refereeUserId are required",
  REFERRAL_NOT_FOUND_OR_COMPLETED: "Referral not found or already completed",
  REFERRER_NOT_FOUND: "Referrer not found",
  REFERRAL_COMPLETED: "Referral completed and reward credited",
  CANNOT_REPORT_SELF: "You cannot report yourself.",
  REPORT_ALREADY_EXISTS: "You have already reported this user. Please wait for admin review.",
  REPORT_CREATED: "User reported successfully.",
  REPORTS_FETCHED: "Reports fetched successfully.",
  REPORT_NOT_FOUND: "Report not found.",
  REPORT_RESOLVED: "Report resolved successfully.",
  REPORT_DELETED: "Report deleted successfully.",
  EMAIL_ALREADY_SUBSCRIBED: "Your email is already on our updates list!",
  STAY_UPDATED_SUCCESS: "Successfully added to our updates list!",
  STAY_UPDATED_FETCHED: "Update signups fetched",
  SIGNUP_NOT_FOUND: "Signup not found",
  SIGNUP_REMOVED: "Signup removed",
  SUPPORT_TICKET_CREATED: "Support ticket created successfully",
  SUPPORT_TICKETS_FETCHED: "Tickets fetched successfully",
  SUPPORT_TICKET_NOT_FOUND: "Ticket not found or access denied",
  SUPPORT_TICKET_STATUS_UPDATED: "Ticket status updated successfully",
  SUPPORT_TICKET_DETAILS_FETCHED: "Ticket details fetched",
  INVALID_OTP_TYPE: "Invalid OTP type.",
  INVALID_TOKEN_SCOPE: "Invalid token scope.",
  EVENT_ATTENDEES_FETCHED: "Event attendees fetched",
  STATS_FETCHED: "Stats fetched successfully",
});
