module.exports = Object.freeze({
  REGISTRATION_SUCCESS_MESSAGE: "Registered successfully.",
  REGISTRATION_FAILURE_MESSAGE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  REGISTRATION_DEVICE_ID_FAIL:
    "Please Register With Same Device as You Verified Earliar.",
  LOGIN_SUCCESS: "Login Successful.",
  GUEST_LOGIN_SUCCESS: "Guest login successful",
  ACCOUNT_DISABLE: "Account Disable",
  LOGIN_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  EMAIL_NOTFOUND: "Email not Found",
  EMAIL_REQUIRED: "Email is required.",
  INVALID_PASSWORD: "Invalid Password",
  UPDATE_PASSWORD_SUCCESS: "Your password is successfully updated.",
  UPDATE_PASSWORD_FAILURE:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED_MSG:
    "Sorry for inconvenience! Facing something wrong while processing your request.",
  FAILED: "Server error.",
  INNGS_DUPLICATE: "Inngs duplicate data already exist.",
  CREATE_SUCCESS: "Created successfully.",
  SUCCESS: "success",
  ALREADY: "Already exist.",
  DULICATE: "Name/mobile number are already exist.",
  NOT_FOUND: "Not found.",
  DATABASE_ERROR: "Not Getting Parent",
  FAILED_TO_SAVE: "Failed to save user data",
  PASSWORD_NOT_MATCH: "Password and ConfirmPassword not match",
  REGISTRATION_OTP: "OTP has been sent to your registered email",
  CREDENTIALS: "Enter valid credentials",
  OLD_PASSWORD: "Old password is incorrect",
  SEND_OTP: "OTP sent to your email address. OTP will expire in 10 min.",
  UPDATE_STATUS: "Update Status Successfully",
  WITHDRAW_AMOUNT:
    "Withdrawa request approved and balance deducted successfully.",
  WITHDRAW_REQUEST: "Withdraw request initiated successfully.",
  DEPOSIT_AMOUNT: "Deposit amount request initiated successfully.",
  UPDATE_BANK: "Bank details updated successfully.",
  ADD_BANK: "Bank details added successfully.",
  DEVICE_ID: `dLNvpQxZRPykx96jvtjKss:APA91bE6zNwVmvz0TXTwr9Ijl-rkaurwi0WAYx42wq-G3iPSOl04DMjbVAXHDzevxeT2fWtKvmfO_73R9PQ095RPashK8BmNJ8_NTCOB49F2ZZDuw0uN_1TFgm30NgrrYEjXdkiJv4Ho`,
  ACCOUNT_DISABLED: "Your account has been disabled. Please contact support.",
  PENDING_BANK_ACCOUNT: "You already have a pending bank account verification. Please wait for admin approval.",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  CONTACT_ALREADY_EXISTS: "Contact number already exists",
  OTP_SENT_SUCCESS: "OTP sent successfully",
  INVALID_OR_EXPIRED_OTP: "Invalid or expired OTP",
  SESSION_EXPIRED_REGISTER: "Session expired, please register again",
  SESSION_EXPIRED_SIGNUP:
    "Session expired or invalid request. Please start signup again.",
  REGISTRATION_SUCCESSFUL: "Registration successful",
  ORGANIZER_REGISTRATION_SUCCESS:
    "Organizer registration successful. Pending admin approval.",
  OTP_RESENT_SUCCESS: "OTP resent successfully",
  NO_FILES_UPLOADED: "No files uploaded",
  FILES_UPLOADED_SUCCESS: "Files uploaded successfully",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  USER_NOT_FOUND: "User not found",
  LOGIN_SUCCESS_MSG: "Login successful",
  ACCOUNT_STATUS_PREFIX: "Your account status is ",
  WAIT_FOR_ADMIN_APPROVAL: ". Please wait for admin approval.",
  CATEGORY_NAME_REQUIRED: "Category name is required.",
  CATEGORY_RESTORED: "Category restored successfully.",
  CATEGORY_ALREADY_EXISTS: "Category already exists.",
  CATEGORY_CREATED: "Category created successfully.",
  CATEGORIES_FETCHED: "Categories fetched successfully.",
  CATEGORY_NOT_FOUND: "Category not found.",
  CATEGORY_NAME_DUPLICATE: "Category with this name already exists.",
  CATEGORY_UPDATED: "Category updated successfully.",
  CATEGORY_DELETED: "Category deleted successfully.",
  CATEGORY_FEATURED_UPDATED: "Category featured status updated successfully.",
  FEATURED_CATEGORY_LIMIT_REACHED: "Only 4 categories can be featured at a time.",
  PROFILE_UPDATED: "Profile updated successfully.",
  SUPER_ADMIN_UPDATE_NOT_ALLOWED:
    "Updating super admin profile is not allowed.",
  EVENT_CREATED: "Event created successfully.",
  EVENT_NOT_FOUND: "Event not found.",
  EVENTS_FETCHED: "Events fetched successfully.",
  EVENT_SLIDER_UPDATED: "Event slider status updated successfully.",
  EVENT_SLIDER_ONLY_UPCOMING_LIVE:
    "Only Upcoming or Live events can be added to slider.",
  INVALID_FILTER_TYPE: "Invalid filter type provided.",
  LOCATION_REQUIRED: "Latitude and longitude are required for nearYou filter.",
  ACCESS_DENIED_INVALID_ROLE: "Access denied. Invalid role.",
  ACCESS_DENIED_ADMIN_ONLY: "Access denied. Admin only.",
  USER_DELETED_SUCCESS: "User deleted successfully",
  ACCOUNT_DELETED_SUCCESS: "Account deleted successfully",
  COURSE_CREATED_SUCCESS: "Course created successfully",
  COURSE_UPDATED_SUCCESS: "Course updated successfully",
  COURSE_UPDATE_FAILED: "Failed to update course",
  UNAUTHORIZED_COURSE_EDIT: "You are not authorized to edit this course",
  UNAUTHORIZED_EVENT_UPDATE: "Unauthorized to update this event",
  DRAFT_UPDATED: "Draft updated",
  EVENT_PUBLISHED_SUCCESS: "Event published successfully",
  DRAFT_SAVED: "Draft saved",
  LOGIN_REQUIRED_DRAFTS: "Login required to view drafts",
  CANNOT_FOLLOW_SELF: "You cannot follow yourself.",
  ALREADY_FOLLOWING: "Already following this user.",
  FOLLOW_SUCCESS: "User followed successfully.",
  NOT_FOLLOWING: "You are not following this user.",
  UNFOLLOW_SUCCESS: "User unfollowed successfully.",
  FOLLOWERS_FETCHED: "Followers fetched successfully.",
  FOLLOWING_FETCHED: "Following list fetched successfully.",
  BUG_REPORT_SUCCESS: "Bug reported successfully",
  BUGS_FETCHED: "Bugs fetched successfully",
  TITLE_REQUIRED: "Title is required",
  INTERNAL_SERVER_ERROR: "Internal server error",
  UNAUTHORIZED_ACCESS: "Access denied. Unauthorized access.",
  SCHEDULE_DATE_ERROR: "Schedule start date must be before end date",
  FIXED_START_SCHEDULE_ERROR: "Fixed start courses must have exactly one schedule",
  DOCUMENTS_REQUIRED: "At least one document is required.",
  ALREADY_VERIFIED: "You are already verified. Re-submission is not allowed.",
  VERIFICATION_DOCS_UPDATED: "Verification documents updated successfully.",
  INVALID_VERIFICATION_ACTION: "Invalid action. Use 'approve' or 'reject'.",
  DOCUMENT_ID_REQUIRED: "Document ID is required.",
  BUSINESS_PROOF_REJECTION_ERROR: "Approved 'Business Proof' cannot be rejected.",
  REJECTION_REASON_REQUIRED: "Reason is required for rejection.",
  DOCUMENT_STATUS_UPDATED: "Document status updated successfully.",
  USER_SETTING_FETCHED: "User setting fetched successfully",
  USER_SETTING_UPDATED: "User setting updated successfully",
  VERIFICATION_REQUESTS_FETCHED: "Verification requests fetched successfully.",
  DOCUMENT_NOT_FOUND: "Document not found.",
  CATEGORY_STATS_FETCHED: "Category statistics fetched successfully",
  INVALID_ENTITY_MODEL: "Invalid entity model",
  PARENT_COMMENT_NOT_FOUND: "Parent comment not found",
  COMMENT_ADDED: "Comment added successfully",
  COMMENTS_FETCHED: "Comments fetched successfully",
  COMMENT_NOT_FOUND_OR_UNAUTHORIZED: "Comment not found or you are not authorized",
  COMMENT_UPDATED: "Comment updated successfully",
  COMMENT_DELETED: "Comment deleted successfully",
  COMMENT_NOT_FOUND: "Comment not found",
  COMMENT_UNLIKED: "Comment unliked",
  COMMENT_LIKED: "Comment liked",
  PARENT_COMMENT_ID_REQUIRED: "parentCommentId is required",
  REPLIES_FETCHED: "Replies fetched successfully",
  ENTITY_NOT_FOUND: "Entity not found",
  REVIEW_ADDED: "Review added successfully",
  REVIEW_NOT_FOUND_OR_UNAUTHORIZED: "Review not found or not authorized",
  REVIEW_UPDATED: "Review updated successfully",
  REVIEW_DELETED: "Review deleted successfully",
  REVIEWS_FETCHED: "Reviews fetched successfully",
  ORGANIZER_REVIEWS_FETCHED: "Organizer reviews fetched successfully",
  ITEM_ALREADY_IN_WISHLIST: "Item already in wishlist",
  ADDED_TO_WISHLIST: "Added to wishlist",
  ITEM_NOT_FOUND_IN_WISHLIST: "Item not found in wishlist",
  REMOVED_FROM_WISHLIST: "Removed from wishlist",
  WISHLIST_FETCHED: "Wishlist fetched successfully",
  NOTIFICATIONS_FETCHED: "Notifications fetched successfully",
  NOTIFICATION_MARKED_READ: "Notification marked as read",
  ALL_NOTIFICATIONS_MARKED_READ: "All notifications marked as read",
  NOTIFICATION_DELETED: "Notification deleted",
  NOT_ENOUGH_TICKETS: "Not enough tickets available",
  NOT_ENOUGH_SEATS: "Not enough seats available",
  EVENT_OR_COURSE_ID_REQUIRED: "Either eventId or courseId must be provided",
  BOOKING_INITIATED: "Booking initiated",
  PROMO_APPLIED: "Promo code applied successfully",
  INVALID_OR_EXPIRED_PROMO: "Invalid or expired promo code",
  BOOKING_CALCULATION_SUCCESS: "Booking calculation successful",
  TRANSACTION_NOT_FOUND: "Transaction not found",
  TRANSACTION_ALREADY_PAID: "Transaction already paid",
  INVALID_TRANSACTION_STATE: "Transaction is in invalid state to pay",
  REFUND_INITIATED_TICKETS: "Tickets no longer available. Refund initiated.",
  REFUND_INITIATED_SEATS: "Seats no longer available. Refund initiated.",
  BOOKING_CONFIRMED: "Payment successful. Booking confirmed.",
  TICKET_LIST_FETCHED: "Ticket list fetched",
  TICKET_NOT_FOUND: "Ticket not found",
  TICKET_DETAIL_FETCHED: "Ticket detail fetched",
  QR_SCANNED: "QR code scanned",
  EARNINGS_FETCHED: "Earnings fetched successfully",
  BANK_DETAILS_UPDATED: "Bank details updated",
  INVALID_AMOUNT: "Invalid amount",
  INSUFFICIENT_BALANCE: "Insufficient balance",
  PAYOUT_REQUEST_SUBMITTED: "Payout request submitted",
  PENDING_PAYOUTS_FETCHED: "Pending payouts fetched",
  PAYOUT_MARKED_PAID: "Payout marked as paid",
  ADMIN_STATS_FETCHED: "Admin stats fetched",
  PAYOUT_NOT_FOUND: "Payout request not found",
  PAYOUT_NOT_PENDING: "Payout is not pending",
  PAYOUT_APPROVED: "Payout approved",
  PAYOUT_REJECTED: "Payout rejected and refunded",
  FINANCE_STATS_FETCHED: "Finance stats fetched",
  PAYOUTS_FETCHED: "Payouts fetched",
  TRANSACTIONS_FETCHED: "Transactions fetched",
  TAX_ALREADY_EXISTS: "Tax with this name already exists.",
  TAX_CREATED: "Tax created successfully.",
  TAX_UPDATED: "Tax updated successfully.",
  TAX_LIST_FETCHED: "Tax list fetched successfully.",
  TAX_DETAILS_FETCHED: "Tax details fetched successfully.",
  TAX_DELETED: "Tax deleted successfully.",
  PROMO_CODE_EXISTS: "Promo code already exists.",
  PROMO_CODE_CREATED: "Promo code created successfully.",
  PROMO_CODE_UPDATED: "Promo code updated successfully.",
  PROMO_CODES_FETCHED: "Promo codes fetched successfully.",
  PROMO_CODE_DETAILS_FETCHED: "Promo code details fetched successfully.",
  PROMO_CODE_DELETED: "Promo code deleted successfully.",
  BOOKING_EXPIRED: "Booking has expired",
  ALL_TICKETS_CHECKED_IN: "All tickets checked in",
  CHECKED_IN_SUCCESS: "Checked in successfully",
  ATTENDEE_LIST_FORBIDDEN: "You don't have permission to view this event's attendees",
  ATTENDEE_LIST_FETCHED: "Attendees list fetched successfully",
  ATTENDEE_STATS_FORBIDDEN: "You don't have permission to view this event's statistics",
  ATTENDEE_STATS_FETCHED: "Attendee statistics fetched",
  RECENT_BOOKINGS_FETCHED: "Recent bookings fetched successfully",
  PUBLIC_TICKET_DETAIL_FETCHED: "Public ticket detail fetched",
  TICKET_NOT_FOUND_OR_UNAUTHORIZED: "Ticket not found or unauthorized",
  TICKET_URLS_GENERATED: "Ticket URLs generated",
  ORGANIZER_STATS_FETCHED: "Organizer stats fetched successfully",
  CUSTOMER_STATS_FETCHED: "Customer stats fetched successfully",
  USER_STATS_FETCHED: "User specific stats fetched successfully",
  ADMIN_REVENUE_FETCHED: "Admin revenue analytics fetched successfully",
  ORGANIZER_REVENUE_FETCHED: "Organizer revenue analytics fetched successfully",
  TRANSACTION_NOT_FOUND_OR_NOT_PAID: "Transaction not found or not paid",
  ATTENDEES_CREATED: "Attendees created successfully",
  MY_ATTENDEES_FETCHED: "Your attendees fetched successfully",
  ATTENDEE_DETAILS_FETCHED: "Attendee details fetched successfully",
  QR_CODE_REQUIRED: "QR code data is required",
  CANNOT_BLOCK_SELF: "You cannot block yourself.",
  USER_ALREADY_BLOCKED: "User already blocked.",
  USER_BLOCKED: "User blocked successfully.",
  USER_NOT_BLOCKED: "User is not blocked.",
  USER_UNBLOCKED: "User unblocked successfully.",
  BLOCKED_USERS_FETCHED: "Blocked users fetched successfully.",
  NO_FILE_UPLOADED: "No file uploaded",
  FILE_UPLOADED: "File uploaded successfully",
  FILE_UPLOAD_ERROR: "Error uploading file",
  CONTACT_REQUIRED_FIELDS: "Name, Email and Message are required",
  MESSAGE_SENT: "Message sent successfully",
  CONTACTS_FETCHED: "Contacts fetched successfully",
  CONTACT_ID_REQUIRED: "Contact ID is required",
  CONTACT_DELETED: "Contact deleted successfully",
  CONTACT_UPDATE_REQUIRED_FIELDS: "Contact ID and Status are required",
  INVALID_STATUS: "Invalid status",
  CONTACT_NOT_FOUND: "Contact not found",
  CONTACT_STATUS_UPDATED: "Contact status updated successfully",
  COURSE_PROMO_PACKAGES_FETCHED: "Active course promotion packages retrieved successfully",
  COURSE_PROMO_UNAUTHORIZED: "You are not authorized to promote this course",
  PROMO_PACKAGE_NOT_FOUND: "Promotion package not found or inactive",
  PROMO_ACTIVATED: "Promotion activated successfully",
  PROMO_PACKAGES_FETCHED: "Active promotion packages fetched successfully.",
  EVENT_NOT_FOUND_OR_NOT_ORGANIZER: "Event not found or you are not the organizer.",
  EVENT_ALREADY_FEATURED: "This event is already actively featured.",
  FAQS_FETCHED: "FAQs fetched successfully",
  FAQ_CREATED: "FAQ created successfully",
  FAQ_NOT_FOUND: "FAQ not found",
  FAQ_UPDATED: "FAQ updated successfully",
  FAQ_DELETED: "FAQ deleted successfully",
  SETTING_NOT_FOUND: "Setting not found",
  SETTING_FETCHED: "Setting fetched",
  SETTING_UPDATED: "Setting updated",
  SETTINGS_FETCHED: "All settings fetched",
  INVALID_ORGANIZER_ID: "Invalid organizer ID",
  ORGANIZER_TRANSACTIONS_FETCHED: "Organizer transactions fetched successfully",
  FETCH_TRANSACTIONS_FAILED: "Failed to fetch transactions",
  WALLET_HISTORY_FETCHED: "Wallet history fetched successfully",
  FETCH_WALLET_HISTORY_FAILED: "Failed to fetch wallet history",
  PAYOUT_HISTORY_FETCHED: "Payout history fetched successfully",
  FETCH_PAYOUTS_FAILED: "Failed to fetch payouts",
  FETCH_STATS_FAILED: "Failed to fetch statistics",
  ORGANIZER_DASHBOARD_FETCHED: "Organizer dashboard data fetched successfully",
  FETCH_DASHBOARD_FAILED: "Failed to fetch dashboard data",
  FETCH_PROMO_PACKAGES_FAILED: "Active promotion packages fetched successfully.",
  NEW_PROMO_PURCHASED: "New Event Promotion Purchased",
  SERVER_ERROR: "Server Error",
  PROMO_PACKAGE_CREATED: "Promotion package created successfully.",
  PROMO_PACKAGE_UPDATED: "Promotion package updated successfully.",
  PROMO_PACKAGE_DETAILS_FETCHED: "Promotion package details fetched successfully.",
  PROMO_PACKAGE_DELETED: "Promotion package deleted successfully.",
  REFERRAL_CODE_FETCHED: "Referral code fetched",
  REFERRAL_STATS_FETCHED: "Referral stats fetched",
  EMAIL_ALREADY_INVITED: "This email has already been invited by you",
  USER_ALREADY_REGISTERED: "This user is already registered on Bondy",
  INVITE_SENT: "Invite sent successfully",
  REFERRAL_REQUIRED_FIELDS: "referralCode and refereeUserId are required",
  REFERRAL_NOT_FOUND_OR_COMPLETED: "Referral not found or already completed",
  REFERRER_NOT_FOUND: "Referrer not found",
  REFERRAL_COMPLETED: "Referral completed and reward credited",
  CANNOT_REPORT_SELF: "You cannot report yourself.",
  REPORT_ALREADY_EXISTS: "You have already reported this user. Please wait for admin review.",
  REPORT_CREATED: "User reported successfully.",
  REPORTS_FETCHED: "Reports fetched successfully.",
  REPORT_NOT_FOUND: "Report not found.",
  REPORT_RESOLVED: "Report resolved successfully.",
  REPORT_DELETED: "Report deleted successfully.",
  EMAIL_ALREADY_SUBSCRIBED: "Your email is already on our updates list!",
  STAY_UPDATED_SUCCESS: "Successfully added to our updates list!",
  STAY_UPDATED_FETCHED: "Update signups fetched",
  SIGNUP_NOT_FOUND: "Signup not found",
  SIGNUP_REMOVED: "Signup removed",
  SUPPORT_TICKET_CREATED: "Support ticket created successfully",
  SUPPORT_TICKETS_FETCHED: "Tickets fetched successfully",
  SUPPORT_TICKET_NOT_FOUND: "Ticket not found or access denied",
  SUPPORT_TICKET_STATUS_UPDATED: "Ticket status updated successfully",
  SUPPORT_TICKET_DETAILS_FETCHED: "Ticket details fetched",
  INVALID_OTP_TYPE: "Invalid OTP type.",
  INVALID_TOKEN_SCOPE: "Invalid token scope.",
  EVENT_ATTENDEES_FETCHED: "Event attendees fetched",
  STATS_FETCHED: "Stats fetched successfully",
  // ── Booking / Cancellation / Refund ──
  BOOKING_CANCELLED: "Booking cancelled successfully",
  BOOKING_CANCEL_NOT_ALLOWED: "Booking cancellation is not allowed per refund policy",
  REFUND_PROCESSED: "Refund processed successfully",
  EVENT_CANCELLED: "Event cancelled. All bookings refunded.",
  COURSE_CANCELLED: "Course cancelled. All bookings refunded.",
  BATCH_CANCELLED: "Batch cancelled. Affected bookings refunded.",
  ALREADY_CANCELLED: "This booking is already cancelled",
  CANNOT_CANCEL_CHECKED_IN: "Cannot cancel a checked-in booking",
  CANNOT_CANCEL_PAST: "Cannot cancel a past event/course booking",
  TICKET_TYPE_NOT_FOUND: "Ticket type not found",
  BATCH_NOT_FOUND: "Batch not found",
  TICKET_SALES_NOT_STARTED: "Ticket sales have not started yet",
  TICKET_SALES_ENDED: "Ticket sales have ended",
  NOT_ENOUGH_TICKETS_FOR_TYPE: "Not enough tickets available for this ticket type",
  BATCH_FULL: "This batch is full",
  COURSE_NOT_FOUND: "Course not found",
  BATCH_INACTIVE: "This batch is no longer active",
  EVENT_NOT_ACTIVE: "This event is not available for booking",
  COURSE_NOT_ACTIVE: "This course is not available for booking",
  CANCEL_EVENT_UNAUTHORIZED: "You are not authorized to cancel this event",
  CANCEL_COURSE_UNAUTHORIZED: "You are not authorized to cancel this course",
  CANCELLATION_REASONS_FETCHED: "Cancellation reasons fetched successfully",
  INVALID_CANCELLATION_REASON: "Invalid cancellation reason",
  CANCELLATION_FEE_APPLIED: "Cancellation fee applied to refund",
  // ── Individual Ticket System ─────────────────────────────────────────────
  TAMPERED_QR: "QR code is invalid or has been tampered with",
  TICKET_CANCELLED: "This ticket has been cancelled and cannot be used for entry",
  TICKET_REFUNDED: "This ticket has been refunded and cannot be used for entry",
  TICKET_EXPIRED: "This ticket has expired",
  TICKETS_GENERATED: "Individual tickets generated successfully",
  SCAN_AUDIT_RECORDED: "Scan recorded in audit trail",
  TICKET_ALREADY_CHECKED_IN: "This ticket has already been checked in",
  INDIVIDUAL_TICKET_FETCHED: "Individual ticket details fetched successfully",
  MY_TICKETS_FETCHED: "My tickets fetched successfully",
  CANNOT_CREATE_ATTENDEES_X_HAS_EXPIRED: "Booking type has expired",
  YOU_MUST_PROVIDE_EXACTLY_X_ATTENDEE_S: "Invalid attendee count",
  ATTENDEES_ALREADY_CREATED_FOR_THIS_TRANS: "Attendees already created for this transaction",
  EVENT_OR_COURSE_NOT_FOUND: "Event or Course not found",
  YOU_ARE_NOT_AUTHORIZED_TO_VIEW_ATTENDEES: "You are not authorized to view attendees for this item",
  BOOKING_NOT_FOUND: "Booking not found",
  BOOKING_IS_NOT_PAID: "Booking is not paid",
  THIS_BOOKING_DOES_NOT_BELONG_TO_THE_SELE: "This booking does not belong to the selected event/course",
  ALL_TICKETS_FOR_THIS_BOOKING_ARE_ALREADY: "All tickets for this booking are already checked in",
  ENTITYID_IS_REQUIRED_FOR_USER_PROFILE_SC: "entityId is required for User profile scans",
  NO_PAID_BOOKING_FOUND_FOR_THIS_USER: "No paid booking found for this user",
  TRANSACTION_NOT_FOUND_1: "Transaction not found",
  THIS_TICKET_DOES_NOT_BELONG_TO_THE_SELEC: "This ticket does not belong to the selected event/course",
  YOU_ARE_NOT_AUTHORIZED_TO_CHECK_IN_ATTEN: "You are not authorized to check-in attendees for this",
  YOU_ARE_NOT_AUTHORIZED_TO_VIEW_THIS_TICK: "You are not authorized to view this ticket",
  YOU_ARE_NOT_AUTHORIZED_TO_CHECK_IN_ATTEN_1: "You are not authorized to check-in attendees for this event/course",
  THIS_SPECIFIC_TICKET_HAS_ALREADY_BEEN_SC: "This specific ticket has already been scanned and checked in",
  INDIVIDUAL_TICKET_NOT_FOUND: "Individual ticket not found",
  EVENTID_OR_COURSEID_IS_REQUIRED_FOR_USER: "eventId or courseId is required for User profile scans",
  THIS_TICKET_DOES_NOT_BELONG_TO_THE_SELEC_1: "This ticket does not belong to the selected event",
  THIS_TICKET_DOES_NOT_BELONG_TO_THE_SELEC_2: "This ticket does not belong to the selected course",
  TRANSACTION_IS_NOT_PAID: "Transaction is not PAID",
  TRANSACTION_BOOKINGTYPE_COURSE_PASS_TRAN: "${transaction.bookingType === COURSE ? Pass : (transaction.bookingType || Event",
  NO_AVAILABLE_ATTENDEE_FOUND_TO_CHECK_IN: "No available attendee found to check-in",
  TICKET_CODE_OR_QR_CODE_IS_REQUIRED: "Ticket code or QR code is required",
  TICKET_VERIFICATION_RESULT: "Ticket verification result",
  YOU_ARE_NOT_AUTHORIZED_TO_VERIFY_TICKETS: "You are not authorized to verify tickets for this",
  TICKET_VERIFIED_SUCCESSFULLY: "Ticket verified successfully",
  TICKET_NOT_FOUND_FOR_THIS_SUB_BOOKING_ID: "Ticket not found for this sub-booking ID",
  THIS_TICKET_DOES_NOT_BELONG_TO_THE_SELEC_3: "This ticket does not belong to the selected",
  YOU_ARE_NOT_AUTHORIZED_TO_VIEW_DETAILS_F: "You are not authorized to view details for this",
  BANNER_CREATED_SUCCESSFULLY: "Banner created successfully",
  BANNERS_FETCHED_SUCCESSFULLY: "Banners fetched successfully",
  ACTIVE_BANNERS_FETCHED_SUCCESSFULLY: "Active banners fetched successfully",
  BANNER_NOT_FOUND: "Banner not found",
  BANNER_UPDATED_SUCCESSFULLY: "Banner updated successfully",
  BANNER_STATUS_TOGGLED_SUCCESSFULLY: "Banner status toggled successfully",
  BANNER_DELETED_SUCCESSFULLY: "Banner deleted successfully",
  TICKET_TYPE_NOT_FOUND_FOR_TICKETID_X: "Ticket type not found for ticketId:",
  SALES_NOT_STARTED_FOR_TICKET_TYPE_X: "Sales not started for ticket type:",
  SALES_ENDED_FOR_TICKET_TYPE_X: "Sales ended for ticket type:",
  NOT_ENOUGH_TICKETS_AVAILABLE_FOR_X: "Not enough tickets available for:",
  AT_LEAST_ONE_ONGOING_SLOT_IS_REQUIRED: "At least one ongoing slot is required",
  BATCH_NOT_FOUND_X: "Batch not found:",
  BATCH_INACTIVE_X: "Batch inactive:",
  BOOKING_IS_CLOSED_FOR_SLOT_X_ON_X_THIS_D: "Booking is closed for slot: on (this date is cancelled)",
  BOOKING_IS_CLOSED_FOR_SLOT_X_CUT_OFF_TIM: "Booking is closed for slot: (cut-off time reached)",
  BATCH_FULL_X: "Batch full:",
  BOOKING_IS_CLOSED_FOR_THIS_COURSE_CUT_OF: "Booking is closed for this course (cut-off time reached)",
  _1_MONTH_PASS_IS_NOT_ENABLED_FOR_THIS_CLA: "1 Month Pass is not enabled for this class",
  _3_MONTH_PASS_IS_NOT_ENABLED_FOR_THIS_CLA: "3 Month Pass is not enabled for this class",
  AT_LEAST_ONE_ONGOING_SLOT_OR_PASS_SELECT: "At least one ongoing slot or pass selection is required",
  AT_LEAST_ONE_ONGOING_SLOT_SELECTION_IS_R: "At least one ongoing slot selection is required",
  REFUND_PREVIEW_CALCULATED_SUCCESSFULLY: "Refund preview calculated successfully",
  EVENT_IS_ALREADY_CANCELLED: "Event is already cancelled",
  THIS_SPECIFIC_DATE_IS_ALREADY_CANCELLED: "This specific date is already cancelled for this batch",
  YOU_ARE_NOT_AUTHORIZED_TO_EDIT_THIS_COUR: "You are not authorized to edit this course",
  CANNOT_ADJUST_RESERVED_SEATS_FOR_A_CANCE: "Cannot adjust reserved seats for a cancelled batch",
  SEATS_LIMIT_X_CANNOT_BE_LESS_THAN_ENROLL: "Seats limit () cannot be less than enrolled count () + externally reserved seats ()",
  RESERVED_SEATS_UPDATED_SUCCESSFULLY: "Reserved seats updated successfully",
  YOU_DONT_HAVE_PERMISSION_TO_VIEW_THIS_EV: "You dont have permission to view this events attendees",
  YOU_DONT_HAVE_PERMISSION_TO_VIEW_THIS_CO: "You dont have permission to view this courses attendees",
  YOU_DONT_HAVE_PERMISSION_TO_VIEW_THIS_EV_1: "You dont have permission to view this events statistics",
  INVALID_ENTITY_MODEL_1: "Invalid entity model",
  COMMENTS_FETCHED_SUCCESSFULLY: "Comments fetched successfully",
  COMMENT_UPDATED_SUCCESSFULLY: "Comment updated successfully",
  PARENT_COMMENT_NOT_FOUND_1: "Parent comment not found",
  BATCH_WITH_ID_X_NOT_FOUND_FOR_THIS_COURS: "Batch with ID not found for this course",
  CANNOT_EDIT_A_COURSE_THAT_HAS_ALREADY_EN: "Cannot edit a course that has already ended",
  ONCE_A_COURSE_IS_PUBLISHED_IT_CANNOT_BE: "Once a course is published, it cannot be changed back to a draft",
  COURSE_TITLE_IS_REQUIRED_FOR_A_PUBLISHED: "Course title is required for a published course",
  ENROLLMENT_TYPE_IS_REQUIRED_FOR_A_PUBLIS: "Enrollment type is required for a published course",
  COURSE_CATEGORY_IS_REQUIRED_FOR_A_PUBLIS: "Course category is required for a published course",
  START_AND_END_DATES_ARE_REQUIRED_FOR_A_P: "Start and end dates are required for a published course",
  START_DATE_IS_REQUIRED_FOR_A_PUBLISHED_C: "Start date is required for a published course",
  TOTAL_SESSIONS_IS_REQUIRED_FOR_A_PUBLISH: "Total sessions is required for a published course",
  PRICE_IS_REQUIRED_FOR_A_PUBLISHED_COURSE: "Price is required for a published course",
  VENUE_ADDRESS_WITH_VALID_LATITUDE_AND_LO: "Venue address with valid latitude and longitude is required for a published course",
  AT_LEAST_ONE_BATCH_IS_REQUIRED_FOR_A_PUB: "At least one batch is required for a published course",
  BATCH_AT_INDEX_X_MUST_HAVE_BATCHNAME_STA: "Batch at index must have batchName, startTime, endTime, days, and seats",
  CANNOT_MODIFY_THE_START_DATE_TIME_OF_A_C: "Cannot modify the start date/time of a course that is already live",
  START_DATE_MUST_BE_IN_THE_FUTURE_FOR_UPC: "Start date must be in the future for upcoming courses",
  END_DATE_MUST_BE_IN_THE_FUTURE: "End date must be in the future",
  START_DATE_MUST_BE_BEFORE_END_DATE: "Start date must be before end date",
  SEATS_LIMIT_X_CANNOT_BE_LESS_THAN_ENROLL_1: "Seats limit () cannot be less than enrolled count () + externally reserved seats () for batch ${batch.batchName || (existingBatch ? existingBatch.batchName :",
  INVALID_COURSE_ID_FORMAT: "Invalid course ID format",
  COURSE_NOT_FOUND_1: "Course not found",
  YOU_ARE_NOT_AUTHORIZED_TO_DELETE_THIS_CO: "You are not authorized to delete this course",
  ONLY_DRAFT_COURSES_CAN_BE_DELETED: "Only draft courses can be deleted",
  DRAFT_COURSE_DELETED_SUCCESSFULLY: "Draft course deleted successfully",
  YOU_ARE_NOT_AUTHORIZED_TO_ASSIGN_STAFF_T: "You are not authorized to assign staff to this course",
  ONE_OR_MORE_PROVIDED_USER_IDS_ARE_NOT_VA: "One or more provided user IDs are not valid staff members",
  STAFF_SUCCESSFULLY_ASSIGNED_TO_THE_COURS: "Staff successfully assigned to the course",
  ORGANIZER_HAS_NO_COURSES_FOR_ANALYTICS: "Organizer has no courses for analytics",
  ORGANIZER_COURSES_ANALYTICS_SUMMARY_RETR: "Organizer courses analytics summary retrieved successfully",
  YOU_ARE_NOT_AUTHORIZED_TO_VIEW_ANALYTICS: "You are not authorized to view analytics for this course",
  COURSE_ANALYTICS_RETRIEVED_SUCCESSFULLY: "Course analytics retrieved successfully",
  BOOKING_CUT_OFF_OPTIONS_RETRIEVED_SUCCES: "Booking cut-off options retrieved successfully",
  YOUR_EVENT_IS_ALREADY_LIVE: "Your event is already live",
  TOTAL_EVENT_SEATS_X_CANNOT_BE_LESS_THAN: "Total event seats () cannot be less than booked count () + externally reserved seats ()",
  TOTAL_EVENT_SEATS_X_CANNOT_BE_LESS_THAN_1: "Total event seats () cannot be less than externally reserved seats ()",
  ONCE_AN_EVENT_IS_PUBLISHED_IT_CANNOT_BE: "Once an event is published, it cannot be changed back to a draft",
  EVENT_TITLE_IS_REQUIRED_FOR_A_PUBLISHED: "Event title is required for a published event",
  EVENT_CATEGORY_IS_REQUIRED_FOR_A_PUBLISH: "Event category is required for a published event",
  START_AND_END_DATES_ARE_REQUIRED_FOR_A_P_1: "Start and end dates are required for a published event",
  VENUE_ADDRESS_WITH_VALID_LATITUDE_AND_LO_1: "Venue address with valid latitude and longitude is required for a published event",
  AT_LEAST_ONE_TICKET_IS_REQUIRED_FOR_A_PU: "At least one ticket is required for a published event",
  TICKET_AT_INDEX_X_MUST_HAVE_TICKETNAME_P: "Ticket at index must have ticketName, price, and qty",
  CANNOT_MODIFY_THE_START_DATE_TIME_OF_AN: "Cannot modify the start date/time of an event that is already live",
  START_DATE_MUST_BE_IN_THE_FUTURE_FOR_UPC_1: "Start date must be in the future for upcoming events",
  MINIMUM_AGE_MUST_BE_SPECIFIED_AND_NON_NE: "Minimum age must be specified and non-negative for MIN_AGE type",
  BOTH_MINIMUM_AND_MAXIMUM_AGE_MUST_BE_SPE: "Both minimum and maximum age must be specified and non-negative for RANGE type",
  MINIMUM_AGE_MUST_BE_LESS_THAN_MAXIMUM_AG: "Minimum age must be less than maximum age",
  REFUND_POLICIES_RETRIEVED_SUCCESSFULLY: "Refund policies retrieved successfully",
  INVALID_EVENT_ID_FORMAT: "Invalid event ID format",
  EVENT_NOT_FOUND_1: "Event not found",
  YOU_ARE_NOT_AUTHORIZED_TO_DELETE_THIS_EV: "You are not authorized to delete this event",
  ONLY_DRAFT_EVENTS_CAN_BE_DELETED: "Only draft events can be deleted",
  DRAFT_EVENT_DELETED_SUCCESSFULLY: "Draft event deleted successfully",
  YOU_ARE_NOT_AUTHORIZED_TO_ASSIGN_STAFF_T_1: "You are not authorized to assign staff to this event",
  STAFF_SUCCESSFULLY_ASSIGNED_TO_THE_EVENT: "Staff successfully assigned to the event",
  YOU_ARE_NOT_AUTHORIZED_TO_VIEW_ANALYTICS_1: "You are not authorized to view analytics for this event",
  EVENT_ANALYTICS_RETRIEVED_SUCCESSFULLY: "Event analytics retrieved successfully",
  ORGANIZER_HAS_NO_LISTINGS_FOR_ANALYTICS: "Organizer has no listings for analytics",
  ORGANIZER_EVENTS_AND_COURSES_ANALYTICS_S: "Organizer events and courses analytics summary retrieved successfully",
  EXPLORE_LIST_FETCHED_SUCCESSFULLY: "Explore list fetched successfully",
  ID_AND_TYPE_EVENT_COURSE_ARE_REQUIRED: "id and type (event/course) are required",
  INVALID_TYPE_MUST_BE_EVENT_OR_COURSE: "Invalid type. Must be event or course",
  SHARE_URL_GENERATED_SUCCESSFULLY: "Share URL generated successfully",
  SEARCH_RESULTS_FETCHED_SUCCESSFULLY: "Search results fetched successfully",
  USER_NOT_AUTHENTICATED: "User not authenticated",
  QUERY_IS_REQUIRED: "Query is required",
  SEARCH_QUERY_SAVED_TO_HISTORY_SUCCESSFUL: "Search query saved to history successfully",
  RECENT_SEARCHES_RETRIEVED_SUCCESSFULLY: "Recent searches retrieved successfully",
  SEARCH_QUERY_DELETED_SUCCESSFULLY: "Search query deleted successfully",
  ALL_SEARCH_HISTORY_CLEARED_SUCCESSFULLY: "All search history cleared successfully",
  TRENDING_SEARCHES_RETRIEVED_SUCCESSFULLY: "Trending searches retrieved successfully",
  NOTIFICATIONS_DELETED_SUCCESSFULLY: "Notifications deleted successfully",
  BANK_NAME_HOLDER_NAME_AND_ACCOUNT_NUMBER: "Bank Name, Holder Name, and Account Number are required.",
  BANK_ACCOUNT_ADDED_SUCCESSFULLY_WAITING: "Bank account added successfully. Waiting for admin approval.",
  BANK_ACCOUNT_NOT_FOUND: "Bank account not found.",
  ONLY_APPROVED_BANK_ACCOUNTS_CAN_BE_SET_A: "Only approved bank accounts can be set as primary.",
  PRIMARY_BANK_ACCOUNT_UPDATED_SUCCESSFULL: "Primary bank account updated successfully.",
  BANK_ACCOUNT_REMOVED_SUCCESSFULLY: "Bank account removed successfully.",
  BANK_ACCOUNTS_FETCHED_SUCCESSFULLY: "Bank accounts fetched successfully.",
  MINIMUM_PAYOUT_AMOUNT_IS_X: "Minimum payout amount is ₮",
  SELECTED_BANK_ACCOUNT_NOT_FOUND: "Selected bank account not found.",
  SELECTED_BANK_ACCOUNT_IS_NOT_APPROVED: "Selected bank account is not approved.",
  NO_APPROVED_BANK_ACCOUNT_FOUND_FOR_PAYOU: "No approved bank account found for payout.",
  REFERRAL_REWARDS_FETCHED: "Referral rewards fetched",
  REPORT_IS_ALREADY_X: "Report is already processed",
  TIMEZONE_UPDATED_SUCCESSFULLY: "Timezone updated successfully",
  USER_PROFILE_FETCHED_SUCCESSFULLY: "User profile fetched successfully",
  USER_LIST_FETCHED_SUCCESSFULLY: "User list fetched successfully",
  USER_X_SUCCESSFULLY: "User successfully",
  TYPE_IS_REQUIRED_LOGIN_CUSTOMER_ORGANIZE: "Type is required (LOGIN, CUSTOMER, ORGANIZER, FORGOT_PASSWORD).",
  TYPE_IS_REQUIRED_LOGIN_CUSTOMER_ORGANIZE_1: "Type is required (LOGIN, CUSTOMER, ORGANIZER).",
  OTP_VERIFIED_SUCCESSFULLY_USE_THE_TOKEN: "OTP verified successfully. Use the token to reset password.",
  RESET_TOKEN_REQUIRED: "Reset token required.",
  INVALID_OR_EXPIRED_RESET_TOKEN: "Invalid or expired reset token.",
  INVALID_OLD_PASSWORD: "Invalid old password.",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
  STAFF_ACCOUNT_NOT_FOUND: "Staff account not found",
  STAFF_MEMBER_ADDED_SUCCESSFULLY: "Staff member added successfully",
  STAFF_LIST_RETRIEVED_SUCCESSFULLY: "Staff list retrieved successfully",
  INVALID_EMAIL_OR_PASSWORD_1: "Invalid email or password",
  STAFF_LOGGED_IN_SUCCESSFULLY: "Staff logged in successfully",
  ASSIGNED_LIST_RETRIEVED_SUCCESSFULLY: "Assigned list retrieved successfully",
  SCAN_HISTORY_RETRIEVED_SUCCESSFULLY: "Scan history retrieved successfully",
  STAFF_MEMBER_NOT_FOUND_OR_ACCESS_DENIED: "Staff member not found or access denied",
  STAFF_MEMBER_UPDATED_SUCCESSFULLY: "Staff member updated successfully",
  STAFF_MEMBER_REMOVED_SUCCESSFULLY: "Staff member removed successfully",
  ONLY_ORGANIZERS_CAN_UPDATE_ORGANIZER_INF: "Only organizers can update organizer info",
  ORGANIZER_INFO_SUBMITTED_SUCCESSFULLY_YO: "Organizer info submitted successfully. Your account is now under review.",
  USER_IS_NOT_AN_ORGANIZER: "User is not an organizer",
  INVALID_ACTION_USE_APPROVE_OR_REJECT: "Invalid action. Use approve or reject.",
  ORGANIZER_ACCOUNT_SUCCESSFULLY_X: "Organizer account successfully .",
  INVALID_APPTHEME_VALUE_ALLOWED_VALUES_LI: "Invalid appTheme value. Allowed values: light",
  INVALID_LANGUAGE_VALUE_ALLOWED_VALUES_EN: "Invalid language value. Allowed values: English",
  BOTH_FRONT_AND_BACK_IMAGES_ARE_REQUIRED: "Both front and back images are required for National ID.",
  BOTH_FRONT_AND_BACK_IMAGES_ARE_REQUIRED_1: "Both front and back images are required for Driving Licence.",
  BANK_NAME_HOLDER_NAME_AND_ACCOUNT_NUMBER_1: "Bank Name, Holder Name, and Account Number are required for Bank Verification.",
  BUSINESS_NAME_AND_BUSINESS_CATEGORY_ARE: "Business Name and Business Category are required for Business Verification.",
  NO_VERIFICATION_DETAILS_PROVIDED_PLEASE: "No verification details provided. Please submit nationalId, drivingLicence, bankVerification, or businessVerification.",
  INVALID_VERIFICATION_TYPE_MUST_BE_NATION: "Invalid verification type. Must be nationalId",
  NATIONAL_ID_HAS_NOT_BEEN_SUBMITTED_YET: "National ID has not been submitted yet.",
  DRIVING_LICENCE_HAS_NOT_BEEN_SUBMITTED_Y: "Driving Licence has not been submitted yet.",
  BANK_DETAILS_NOT_FOUND: "Bank details not found.",
  BUSINESS_DETAILS_HAVE_NOT_BEEN_SUBMITTED: "Business details have not been submitted yet.",
  COUNTRY_CODE_AND_CONTACT_NUMBER_ARE_REQU: "Country code and contact number are required.",
  OTP_SENT_SUCCESSFULLY_TO_YOUR_PHONE_NUMB: "OTP sent successfully to your phone number.",
  COUNTRY_CODE_AND_CONTACT_NUMBER_ARE_REQU_1: "Country code and contact number are required to resend OTP.",
  OTP_RESENT_SUCCESSFULLY_TO_YOUR_PHONE_NU: "OTP resent successfully to your phone number.",
  OTP_IS_REQUIRED: "OTP is required.",
  PHONE_NUMBER_VERIFIED_SUCCESSFULLY: "Phone number verified successfully.",
  EMAIL_IS_REQUIRED: "Email is required.",
  OTP_SENT_SUCCESSFULLY_TO_YOUR_EMAIL_ADDR: "OTP sent successfully to your email address.",
  EMAIL_IS_REQUIRED_TO_RESEND_OTP: "Email is required to resend OTP.",
  OTP_RESENT_SUCCESSFULLY_TO_YOUR_EMAIL_AD: "OTP resent successfully to your email address.",
  EMAIL_VERIFIED_SUCCESSFULLY: "Email verified successfully.",
  BANK_NAME_IS_REQUIRED: "Bank Name is required.",
  BANK_NAME_ALREADY_EXISTS: "Bank Name already exists.",
  BANK_ADDED_SUCCESSFULLY: "Bank added successfully.",
  BANK_NOT_FOUND: "Bank not found.",
  BANK_UPDATED_SUCCESSFULLY: "Bank updated successfully.",
  BANK_DELETED_SUCCESSFULLY: "Bank deleted successfully.",
  ACTIVE_BANKS_FETCHED_SUCCESSFULLY: "Active banks fetched successfully.",
});
